// This file was generated by Prisma, and assumes you have installed the following:
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const env = process.env.NODE_ENV || "local";
const envFile = `.env.${env}`;
dotenv.config({ path: envFile });

export default defineConfig({
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  typedSql: {
    path: "src/prisma/sql/",
  },
});
